import type { Metadata } from "next";
import "@stream-io/video-react-sdk/dist/css/styles.css";
import "./globals.css";
import { Outfit } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";
import ConvexClerkProvider from "@/components/providers/ConvexClerkProvider";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const outfit = Outfit({subsets:['latin']})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={outfit.className}>
          <ThemeProvider
          attribute="class"
          defaultTheme="system" enableSystem disableTransitionOnChange>
            <SignedIn>
          <div className="min-h-screen">
          <Navbar/>
          <main> {children}</main>
       </div>
      </SignedIn>
      <SignedOut>
        <RedirectToSignIn/>
      </SignedOut>
       </ThemeProvider>
       <Toaster/>
      </body>
    </html>
    </ConvexClerkProvider>
  );
}
